<a href="https://colab.research.google.com/github/Ikwuakor/resume-samples/blob/master/Python_and_Github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
etf = pd.read_csv("https://raw.githubusercontent.com/Ikwuakor/resume-samples/master/ETFs.csv")

In [3]:
etf.head()

  fund_name  ... category_treynor_ratio_10years
0      1305  ...                            NaN
1      1306  ...                            NaN
2      1308  ...                            NaN
3      1309  ...                            NaN
4      1310  ...                            NaN

[5 rows x 104 columns]